import { MenuItem } from '@/types'

export const menuData: MenuItem[] = [
  // Shawarma
  {
    id: '1',
    name: 'Chicken Shawarma',
    description: 'Tender grilled chicken, garlic sauce, fresh veggies, wrapped in soft flatbread',
    price: 2500,
    category: 'shawarma',
    image_url: 'https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=600&q=80',
    available: true,
    created_at: '',
  },
  {
    id: '2',
    name: 'Beef Shawarma',
    description: 'Seasoned beef strips, special house sauce, pickled veggies, toasted wrap',
    price: 3000,
    category: 'shawarma',
    image_url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&q=80',
    available: true,
    created_at: '',
  },
  {
    id: '3',
    name: 'King Combo Shawarma',
    description: 'Double meat, double sauce, extra veggies — the full royal experience',
    price: 4500,
    category: 'shawarma',
    image_url: 'https://images.unsplash.com/photo-1600891964599-f61ba0e24092?w=600&q=80',
    available: true,
    created_at: '',
  },
  {
    id: '4',
    name: 'Mixed Shawarma',
    description: 'Half chicken, half beef, best of both worlds',
    price: 3500,
    category: 'shawarma',
    image_url: 'https://images.unsplash.com/photo-1484723091739-30a097e8f929?w=600&q=80',
    available: true,
    created_at: '',
  },
  // Drinks
  {
    id: '5',
    name: 'Chapman',
    description: 'Classic Nigerian chapman, chilled and refreshing',
    price: 800,
    category: 'drinks',
    image_url: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?w=600&q=80',
    available: true,
    created_at: '',
  },
  {
    id: '6',
    name: 'Zobo',
    description: 'Homemade hibiscus drink, lightly spiced and chilled',
    price: 600,
    category: 'drinks',
    image_url: 'https://images.unsplash.com/photo-1437418747212-8d9709afab22?w=600&q=80',
    available: true,
    created_at: '',
  },
  {
    id: '7',
    name: 'Bottled Water',
    description: 'Ice cold water',
    price: 300,
    category: 'drinks',
    image_url: 'https://images.unsplash.com/photo-1548839140-29a749e1cf4d?w=600&q=80',
    available: true,
    created_at: '',
  },
  // Extras
  {
    id: '8',
    name: 'Extra Sauce',
    description: 'Garlic sauce, hot sauce, or special house sauce',
    price: 200,
    category: 'extras',
    image_url: 'https://images.unsplash.com/photo-1472476443507-c7a5948772fc?w=600&q=80',
    available: true,
    created_at: '',
  },
  {
    id: '9',
    name: 'French Fries',
    description: 'Crispy golden fries, lightly salted',
    price: 1000,
    category: 'extras',
    image_url: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&q=80',
    available: true,
    created_at: '',
  },
  {
    id: '10',
    name: 'Coleslaw',
    description: 'Fresh creamy coleslaw on the side',
    price: 500,
    category: 'extras',
    image_url: 'https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=600&q=80',
    available: true,
    created_at: '',
  },
]